

<h2>Séances de travaux pratiques</h2>

<h3>Premières séances</h3>

<p>
On teste l'instruction d'affichage <kbd>echo</kbd> et ses différents modes d'utilisation.
On fait des boucles pour faire défiler les entiers,
et des boucles imbriquées pour dessiner des figures géométriques.
On ajoute des commentaires pour bien comprendre ce que l'on fait.
</p>

<div style="text-align: right;">
[ <a href="/~torre/Enseignement/TPs/PHP/seances/tp1.php.src">voir la correction</a> ]
</div>

<p>
On recommence les dessins de figures géométriques en se forçant à utiliser des procédures.
</p>

<div style="text-align: right;">
[ <a href="/~torre/Enseignement/TPs/PHP/seances/tp2.php.src">voir la correction</a> ]
</div>


<h3>Sur les tableaux</h3>

<p>
&Eacute;crire les fonctions PHP qui :
</p>

<ul>
<li> affiche tous les éléments d'un tableau,</li>
<li> calcule la moyenne des nombres contenus dans un tableau donné,</li>
<li> compte combien d'éléments sont supérieurs ou égaux à 10,</li>
<li> teste si la note 20 est présente ou non,</li>
<li> détermine la meilleure note obtenue.</li>
</ul>


<div style="text-align: right;">
[ <a href="/~torre/Enseignement/TPs/PHP/seances/tp3.php.src">voir la correction</a> ]
</div>




<h2>Scripts illustratifs de certaines fonctionnalités</h2>

<h3>La base : PHP et HTML</h3>
<ol>
    
	<li> Affichage simple
	    [ <a href="/~torre/Enseignement/TPs/PHP/simple.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/simple.php.src">source</a> ]
	    </li>

	<li> Affichage de code HTML
	    [ <a href="/~torre/Enseignement/TPs/PHP/simple_html.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/simple_html.php.src">source</a> ]
	    </li>

	<li> Affichage changeant
	    [ <a href="/~torre/Enseignement/TPs/PHP/heure.php">démo</a> ][ <a href="/~torre/Enseignement/TPs/PHP/heure.php.src">source</a> ]
	   </li>

      </ol>






<h3>Les variables et leurs types</h3>
      <ol>

	<li> Variables textes et numériques
	    [ <a href="/~torre/Enseignement/TPs/PHP/vars_ab.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/vars_ab.php.src">source</a> ]
	    </li>

	<li> Les tableaux
	    [ <a href="/~torre/Enseignement/TPs/PHP/tab.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/tab.php.src">source</a> ]
	    </li>	    

	<li> Les tableaux associatifs
	    [ <a href="/~torre/Enseignement/TPs/PHP/tab_asso.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/tab_asso.php.src">source</a> ]
	    </li>	    
      </ol>




<h3>Les structures de contrôle</h3>
      <ol>

	<li> Conditionnel
	    [ <a href="/~torre/Enseignement/TPs/PHP/si.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/si.php.src">source</a> ]
	    </li>

	<li> Les boucles <em>pour</em>
	    [ <a href="/~torre/Enseignement/TPs/PHP/pour.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/pour.php.src">source</a> ]
	    </li>

	<li> Les boucles <em>while</em>
	    [ <a href="/~torre/Enseignement/TPs/PHP/while.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/while.php.src">source</a> ]
	    </li>
	    
	<li> Les boucles <em>pour</em> et les tableaux
	    [ <a href="/~torre/Enseignement/TPs/PHP/pour_tab.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/pour_tab.php.src">source</a> ]
	    </li>

	<li> Les boucles <em>while</em> et les tableaux associatifs
	    [ <a href="/~torre/Enseignement/TPs/PHP/while_tab.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/while_tab.php.src">source</a> ]
	    </li>


	<li> Les boucles <em>foreach</em> et les tableaux
	    [ <a href="/~torre/Enseignement/TPs/PHP/foreach_tab.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/foreach_tab.php.src">source</a> ]
	    </li>

	<li> Les boucles <em>foreach</em> et les tableaux associatifs
	    [ <a href="/~torre/Enseignement/TPs/PHP/foreach_tabasso.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/foreach_tabasso.php.src">source</a> ]
	    </li>

      </ol>



<?php echo GenereCodeSectionIsolee('bibli','Procédures, fonctions et bibliothèque','h3'); ?>

      <ol>
	<li> Les fonctions sans résultat (procédure)
	    [ <a href="/~torre/Enseignement/TPs/PHP/proc.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/proc.php.src">source</a> ]
	    </li>

	<li> Les fonctions avec résultat
	    [ <a href="/~torre/Enseignement/TPs/PHP/func.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/func.php.src">source</a> ]
	    </li>

	<li> Une page presque vide utilisant une bibliothèque
	    [ <a href="/~torre/Enseignement/TPs/PHP/vide.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/vide.php.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/bibli.php.src">bibliothèque</a> ]
	    </li>	    
	    
      </ol>





<?php echo GenereCodeSectionIsolee('forms','PHP et les formulaires','h3'); ?>

      <ol>
	
	<li> Un formulaire simple
	    [ <a href="/~torre/Enseignement/TPs/PHP/form.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/form.php.src">source</a> ]
	    </li>

	<li> Un formulaire d'enregistrement
	    [ <a href="/~torre/Enseignement/TPs/PHP/nouveau.html">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/nouveau.html.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/entree.php.src">source PHP</a> ]
	    </li>	    

	<li> Un formulaire de recherche
	    [ <a href="/~torre/Enseignement/TPs/PHP/recherche.html">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/recherche.html.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/search.php.src">source PHP</a> ]
	    </li>

	<li> Un formulaire de chargement de fichiers
	    [ <a href="/~torre/Enseignement/TPs/PHP/upload.html.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/upload.php.src">source PHP</a> ]
	    </li>

      </ol>







<h3>PHP et les bases de données</h3>
      <ol>

	<li> Un formulaire d'enregistrement
	    [ <a href="/~torre/Enseignement/TPs/PHP/nouveaub.html.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/entreeb.php.src">source PHP</a> ]
	    </li>

	<li> Un formulaire de recherche
	    [ <a href="/~torre/Enseignement/TPs/PHP/rechercheb.html.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/searchb.php.src">source PHP</a> ]
	    </li>

	    
      </ol>












<?php echo GenereCodeSectionIsolee('rss','PHP et les fils RSS','h3'); ?>

      <ol>

	<li> Une intégration d'un unique flux
	    [ <a href="/~torre/Enseignement/TPs/PHP/rss.php">démo</a> ][ <a href="/~torre/Enseignement/TPs/PHP/rss.php.src">source</a> ]
	    </li>
	    
	<li> Un agrégateur plus complet
	    [ <a href="/~torre/Enseignement/TPs/PHP/rssplus.php">démo</a> ][ <a href="/~torre/Enseignement/TPs/PHP/rssplus.php.src">source</a> ]
	    </li>
	    
      </ol>





      
      


<h3>PHP et les fichiers</h3>
      <ol>	

	<li> Lire et afficher un fichier
	    [ <a href="/~torre/Enseignement/TPs/PHP/lire.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/lire.php.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/wonder.txt">fichier</a> ]

	    </li>

	<li> Lire et afficher un fichier avec des numéros de ligne
[ <a href="/~torre/Enseignement/TPs/PHP/voir.php?fichier=wonder.txt">démo</a> ][ <a href="/~torre/Enseignement/TPs/PHP/voir.php.src">source</a> ]
</li>
    
	<li> Récupérer des informations dans un fichier
	    [ <a href="/~torre/Enseignement/TPs/PHP/texte.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/texte.php.src">source</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/infos.txt">fichier</a> ]
	    </li>
	    
      </ol>









<h3>Fonctions PHP pour le tri des tableaux</h3>
	<ol>
	
	<li> Les différentes fonctions de tri en PHP
	    [ <a href="/~torre/Enseignement/TPs/PHP/sort.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/sort.php.src">source</a> ]
	    </li>
	    
	</ol>



      

<h3>Génération d'images</h3>
      <ol>

	<li> Créer une image
	    [ <a href="/~torre/Enseignement/TPs/PHP/bouton.html">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/bouton.html.src">source HTML</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/image.php.src">source PHP</a> ]
	    </li>


	<li> Surcharger une image :
	    [ <a href="/~torre/Enseignement/TPs/PHP/rollover.html">démo</a> ][ <a href="/~torre/Enseignement/TPs/PHP/rollover.html.src">source HTML</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/buttafia.php.src">source PHP</a> ]
	    </li>




	<li> Tracer une courbe
	    [ <a href="/~torre/Enseignement/TPs/PHP/courbe.html">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/courbe.html.src">source HTML</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/courbe-d1.php.src">source PHP</a> ]
	    </li>
	    

      </ol>




      

<h3>PHP et la programmation objet</h3>
      <ol>


	<li> Une classe pour les tables HTML
	    [ <a href="/~torre/Enseignement/TPs/PHP/table_class.php.src">classe</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/table_test.php.src">exemple</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/table_test.php">démo</a> ]
	    </li>

      </ol>
    




<h3>PHP et XML</h3>
      <ol>

      <li> Exemple de fichier à traiter
	    [ <a href="/~torre/Enseignement/TPs/PHP/annuaire.xml">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/annuaire.xml.src">fichier XML</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/annuaire.dtd.src">fichier DTD</a> ]
	    </li>

	<li> Un premier parser à la SAX
	    [ <a href="/~torre/Enseignement/TPs/PHP/xml-sax.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/xml-sax.php.src">source PHP</a> ]
	    </li>

	<li> Un second
	    [ <a href="/~torre/Enseignement/TPs/PHP/xml-sax-b.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/xml-sax-b.php.src">source PHP</a> ]
	    </li>

      </ol>
    






<h3>PHP et identification (authentification HTTP)</h3>
      <ol>

	<li> premier essai
	    [ <a href="/~torre/Enseignement/TPs/PHP/identif1.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/identif1.php.src">source PHP</a> ]
	    </li>

	<li> deuxième essai
	    [ <a href="/~torre/Enseignement/TPs/PHP/identif2.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/identif2.php.src">source PHP</a> ]
	    </li>

	<li> troisième essai
	    [ <a href="/~torre/Enseignement/TPs/PHP/identif3.php">démo</a> ][ <a
	    href="/~torre/Enseignement/TPs/PHP/identif3.php.src">source PHP</a> ]
	    </li>


      </ol>
    



<h3>PHP et sessions</h3>

<ol>

<li>enregistrer des informations et les retrouver
<ul>
<li> enregistrer
[ <a href="/~torre/Enseignement/TPs/PHP/quietesvous.php">démo</a> ][ <a
href="/~torre/Enseignement/TPs/PHP/quietesvous.php.src">source PHP</a> ]
</li>
<li> relire
[ <a href="/~torre/Enseignement/TPs/PHP/quivousetes.php">démo</a> ][ <a
href="/~torre/Enseignement/TPs/PHP/quivousetes.php.src">source PHP</a> ]
</li>
</ul>
</li>

<li>identification avec les sessions
<ul>
<li> login
[ <a href="/~torre/Enseignement/TPs/PHP/login.php">démo</a> ][ <a
href="/~torre/Enseignement/TPs/PHP/login.php.src">source PHP</a> ]
</li>
<li> acc&egrave;s
[ <a href="/~torre/Enseignement/TPs/PHP/acces.php">démo</a> ][ <a
href="/~torre/Enseignement/TPs/PHP/acces.php.src">source PHP</a> ]
</li>
<li> logout
[ <a href="/~torre/Enseignement/TPs/PHP/logout.php">démo</a> ][ <a
href="/~torre/Enseignement/TPs/PHP/logout.php.src">source PHP</a> ]
</li>
</ul>
</li>

</ol>





<h3>PHP et l'envoi automatique de mails</h3>
      <ol>

	<li> formulaire d'envoi chez Free
	    [ <a href="/~torre/Enseignement/TPs/PHP/envoimail.php.src">source PHP</a> ]
	    </li>

	<li> formulaire d'envoi avec construction de l'en-tête du mail
	    [ <a href="/~torre/Enseignement/TPs/PHP/envoimailplus.php.src">source PHP</a> ]
	    </li>

      </ol>








<h3>Récupération</h3>
      <ol>

	<li> Tous les exemples de cette section
	    [ <a href="/~torre/Enseignement/TPs/PHP/TP-PHP.tar">archive</a> ]
	    </li>

      </ol>
    







